# Adjust these as needed
# If you have a low-res background and pick a large size, it will look pixelated
# If your picture has different dimensions, it will get resized and may look weird. 
# Crop to avoid this issue
poster_width_in: 8.5
poster_height_in: 11

# Scale of 0 to 255, where 0 is fully transparent and 255 is fully opaque
background_alpha: 200

text:
  # Adjust these as needed
  quran_surah: 73
  include_basmalah: True
  quran_verse_start: 1
  quran_verse_end: 9

  # Fonts
  # From https://github.com/0xzer0x/quran-companion/tree/main/assets/fonts
  # Also from https://github.com/marwan/indopak-quran-text/blob/master/Fonts/v4.2.2%20-%20NORMAL%20SPACING/With%20Waqf%20Lazim%20Indicator/AlQuran-IndoPak-by-QuranWBW.v.4.2.2-WL.ttf
  # Don't touch these unless you know what you're doing

  # Bounding boxes for text - adjust to whatever looks good
  # (0, 0) is top left corner
  # (0, 1) is top right corner
  # (1, 0) is bottom left corner
  # (1, 1) is bottom right corner
  # Specify top left and bottom right corners

  # Don't touch the "source"

  # Find colors in https://htmlcolorcodes.com/color-names/
  ar:
    font_path: "data/01_raw/quran_font.ttf"
    tl: (0.5, 0.05)
    br: (0.9, 0.7)
    source:  "https://github.com/0xzer0x/quran-companion/raw/refs/heads/main/assets/quran.db"
    color: White

  en:
    font_path: "data/01_raw/NotoSansDisplay.ttf"
    tl: (0.1, 0.05)
    br: (0.5, 0.7)
    source: "https://github.com/0xzer0x/quran-companion/raw/refs/heads/main/assets/translations/en_khattab.db"
    color: White

  # Adjust this as needed
  font_size: 56


