poster_width_in: 8.5
poster_height_in: 11

background_image_path: "conf/base/images/background.png"

text:
  quran_surah: 1
  # 1 will include basmalah
  quran_verse_start: 1
  quran_verse_end: 6
  arabic_font_path: "conf/base/fonts/Arabic-Font.ttf"
  english_font_path: "conf/base/fonts/English-Font.ttf"

  # Bounding boxes for text
  # (0, 0) is top left corner
  # (0, 1) is top right corner
  # (1, 0) is bottom left corner
  # (1, 1) is bottom right corner
  # Specify top left and bottom right corners
  arabic_tl: (0.5, 0)
  arabic_br: (1, 1)
  english_tl: (0, 0)
  english_br: (0.5, 1)


