# Adjust these as needed
# If you have a low-res background and pick a large size, it will look pixelated
# If your picture has different dimensions, it will get resized and may look weird. 
# Crop to avoid this issue
poster_width_in: 8.5
poster_height_in: 11

text:
  # Adjust these as needed
  quran_surah: 103
  include_basmalah: True
  quran_verse_start: 1
  quran_verse_end: 4

  # From https://github.com/0xzer0x/quran-companion/tree/main/assets/fonts
  # Don't touch these unless you know what you're doing
  arabic_font_path: "data/01_raw/PakTypeNaskhBasic.ttf"
  english_font_path: "data/01_raw/NotoSansDisplay.ttf"

  # Adjust this as needed
  font_size: 72

  # Bounding boxes for text - adjust to whatever looks good
  # (0, 0) is top left corner
  # (0, 1) is top right corner
  # (1, 0) is bottom left corner
  # (1, 1) is bottom right corner
  # Specify top left and bottom right corners
  arabic_tl: (0.5, 0.1)
  arabic_br: (0.9, 0.6)
  english_tl: (0.1, 0.1)
  english_br: (0.5, 0.6)

  # Don't touch this
  english_source: "https://github.com/0xzer0x/quran-companion/raw/refs/heads/main/assets/translations/en_khattab.db"
  arabic_source: "https://github.com/0xzer0x/quran-companion/raw/refs/heads/main/assets/quran.db"

  # Adjust these as needed
  interline_spacing: 200
  intraline_spacing: 80

# Don't touch this
output_path: "data/03_primary/quran_poster.png"
